name: Compile web page to branch

on:
  #  push:
  #    paths:
  #      - 'tieba-admin-web/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./tieba-admin-web
      - name: Build
        run: npm run build
        working-directory: ./tieba-admin-web
      - name: Create Release
        uses: wow-actions/release-github-action@v2
        with:
          cwd: ./tieba-admin-web
          branches: |
            [
              "+([0-9])?(.{+([0-9]),x}).x",
              "main"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


