name: Compile web page to branch

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cd web
        run: cd ./tieba-admin-web
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create Release
        uses: wow-actions/release-github-action@v2
        # with:
        #   cwd: ./tieba-admin-web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


